### ISSUE TITLE
Manually count game time

### ISSUE THREAD

**Issue by ZeteCx** [FriendsOfGalaxy/galaxy-integration-psn#8]
I wasent sure where to put it,

I'm not a programmer myself but i was wondering if something like that could be implemented. 
I'm aware that ATM there is no way to take 'time played' from our PSN profile and sync it with gog but I was wondering if its possible to manually count the time we play.
I use another app from GitHub called [PlaystationDiscord ](https://github.com/Tustin/PlayStationDiscord), its basically check what my PSN account play and put it on my discord profile as 'playing x'. I was wondering if there is a way to implement something like it to the integration and just manually count hours play?
Again, i have no knowledge in programming and was just wondering if such a thing is possible.

**Comment by FriendsOfGalaxy** [comment]
Hey, 

while game time is a really requested feature and would be a great addition to the plugin doing it this way ( By tracking someones rich presence ) would require some convoluted logic and the results would be really poor.

That is mostly because the time there is tracked per game session and not as your whole time spent in game ( between multiple sessions ). Because of that we would never get your complete time spent in the game and in general could confuse people when the game they spent hundreds of hours on on ps4 suddenly reports as 5 mins total playtime in Galaxy.
